#!/usr/bin/env python3
"""
Rebuilds public/photos/ and lib/photos.ts from the couple's own Zola gallery.

    python3 scripts/build-photos.py

Zola renders its gallery client-side, but the underlying image URLs are present in
the server HTML as https://images.zola.com/<uuid>. Appending ?w=2000 returns the
original (about 1680px on the long edge).

Only the nine photos actually placed in the design are downloaded. Each is resized,
compressed, and given a 16px blurred placeholder inlined as a data URL so pages have
no layout shift and no grey boxes on slow connections.

Requires Pillow:  pip3 install Pillow
"""

import base64
import io
import json
import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, 'public', 'photos')
MANIFEST = os.path.join(ROOT, 'lib', 'photos.ts')
GALLERY = 'https://www.zola.com/wedding/eilands2026/photo'
UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/124.0 Safari/537.36'

def list_gallery():
    """Print every image UUID in the gallery — use this to pick new ones."""
    req = urllib.request.Request(GALLERY, headers={'User-Agent': UA})
    html = urllib.request.urlopen(req).read().decode('utf-8', 'ignore')
    uuids = sorted(set(re.findall(r'https://images\.zola\.com/([a-f0-9-]{36})', html)))
    for u in uuids:
        print(f'https://images.zola.com/{u}?w=2000')
    print(f'\n{len(uuids)} images in the gallery', file=sys.stderr)


def main():
    try:
        from PIL import Image, ImageFilter
    except ImportError:
        sys.exit('Pillow is required:  pip3 install Pillow')

    spec = json.load(open(os.path.join(ROOT, 'scripts', 'photos.json')))
    os.makedirs(OUT_DIR, exist_ok=True)

    # Start from what is already there, so skipped entries survive a rebuild instead
    # of being dropped out of the manifest and breaking the build.
    manifest = {}
    if os.path.exists(MANIFEST):
        existing = open(MANIFEST).read()
        if 'export const PHOTOS = ' in existing:
            body = existing.split('export const PHOTOS = ', 1)[1].rsplit(' as const satisfies', 1)[0]
            manifest = json.loads(body)

    for item in spec:
        # Some images were supplied directly at a higher resolution than the gallery
        # holds. Re-fetching would quietly downgrade them.
        if item.get('skip'):
            print(f"{item['name']:18s} skipped ({item.get('note', 'local original')})")
            continue
        url = f"https://images.zola.com/{item['uuid']}?w=2000"
        raw = urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': UA})).read()
        im = Image.open(io.BytesIO(raw)).convert('RGB')

        w = item['width']
        if im.width > w:
            im = im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)

        path = os.path.join(OUT_DIR, item['name'] + '.jpg')
        im.save(path, 'JPEG', quality=82, optimize=True, progressive=True)

        tiny = im.resize((16, max(1, round(16 * im.height / im.width)))).filter(ImageFilter.GaussianBlur(0.6))
        buf = io.BytesIO()
        tiny.save(buf, 'JPEG', quality=40)

        manifest[item['name']] = {
            'src': f"/photos/{item['name']}.jpg",
            'width': im.width,
            'height': im.height,
            'alt': item['alt'],
            'blur': 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode(),
        }
        print(f"{item['name']:18s} {im.width}x{im.height}  {os.path.getsize(path)//1024} KB")

    header = (
        '// Generated by scripts/build-photos.py — do not edit by hand.\n'
        "// Photos are the couple's own, pulled from their Zola gallery.\n\n"
        'export interface Photo { src: string; width: number; height: number; alt: string; blur: string }\n\n'
        'export const PHOTOS = '
    )
    with open(MANIFEST, 'w') as f:
        f.write(header + json.dumps(manifest, indent=2) + ' as const satisfies Record<string, Photo>\n')

    total = sum(os.path.getsize(os.path.join(OUT_DIR, f)) for f in os.listdir(OUT_DIR))
    print(f'\n{len(manifest)} photos, {total // 1024} KB total')


if __name__ == '__main__':
    if '--list' in sys.argv:
        list_gallery()
    else:
        main()
